import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { api } from '../services/api';

const services = [
 ['FLAT_EMBROIDERY','Bordado plano'],['EMBROIDERY_3D','Bordado 3D'],['APPLIQUE_EMBROIDERY','Bordado aplicado'],['PATCHES','Parches'],['SUBLIMATION','Sublimación'],['FULL_SUBLIMATION','Full sublimado'],['GARMENT_MAKING','Confección'],['UNIFORMS','Uniformes'],['TSHIRTS','Playeras'],['OTHER','Otro']
];
export default function NewOrder() {
  const navigate = useNavigate(); const [error,setError] = useState(''); const [loading,setLoading] = useState(false); const [files,setFiles] = useState([]);
  async function submit(e){ e.preventDefault(); setLoading(true); setError(''); const raw=Object.fromEntries(new FormData(e.currentTarget)); try { const {data: order}=await api.post('/orders',{...raw,quantity:Number(raw.quantity)}); if(files.length){const fd=new FormData(); files.forEach(f=>fd.append('files',f)); await api.post(`/orders/${order.id}/files`,fd,{headers:{'Content-Type':'multipart/form-data'}});} navigate(`/pedido/${order.id}`);} catch(err){setError(err.response?.data?.message||'No se pudo crear el pedido');} finally{setLoading(false);} }
  return <section className="dashboard-page narrow"><div className="page-title"><div><span className="eyebrow">NUEVA SOLICITUD</span><h1>Cuéntanos qué necesitas</h1><p>La fecha que elijas será una fecha solicitada; el equipo confirmará la entrega después de revisar el trabajo.</p></div></div><form className="panel order-form" onSubmit={submit}>{error&&<div className="alert">{error}</div>}<div className="form-grid"><label>Servicio<select name="serviceType" required><option value="">Selecciona…</option>{services.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Producto<input name="product" placeholder="Ej. Gorras, playeras, uniformes" required/></label><label>Cantidad<input name="quantity" type="number" min="1" required/></label><label>Colores<input name="colors" placeholder="Ej. negro, blanco y rojo"/></label><label>Fecha deseada<input name="requestedDate" type="date"/></label><label>Tallas<input name="sizes" placeholder="Ej. S:5, M:10, L:8"/></label><label className="span-2">Detalles<textarea name="notes" rows="5" placeholder="Ubicación del bordado, medidas, tipo de tela, instrucciones especiales…"/></label><label className="span-2 upload-box">Diseños / logos<input type="file" multiple onChange={e=>setFiles([...e.target.files])}/><span>{files.length ? `${files.length} archivo(s) seleccionado(s)` : 'PNG, JPG, PDF, SVG, AI, EPS, CDR u otros archivos de referencia'}</span></label></div><button className="button" disabled={loading}>{loading?'Enviando pedido…':'Enviar pedido'}</button></form></section>;
}
